version: "3.9"
services:
  db:
    image: postgres:15.1-alpine
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mypassword"
      POSTGRES_DB: "menu"
  app:
    build: .
    container_name: fastapi-app
    command: bash -c "uvicorn main:app --host 0.0.0.0"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
        DATABASE_URL: "postgresql://postgres:mypassword@db/menu"
        