version: "3.9"
services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./data/db:/root/db
    environment:
      - DATABASEPATH=db.sqlite3
  app:
    build: .
    container_name: fastapi-app
    command: bash -c "uvicorn main:app --host 0.0.0.0"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
