version: "3.9"
services:
  db:
    image: postgres:15.1-alpine
    ports:
      - "2345:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
  cache:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: fastapi-app
    command: bash -c "uvicorn main:app --host 0.0.0.0"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
